/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ex3;

import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author younghoonkim
 */
public class HolJJackGame extends javax.swing.JFrame {

    /**
     * Creates new form HolJJackGame
     */
    
    //Service object mainly process business logic
    private final ServiceInter service;
    //CardLayout to shift cards
    private final CardLayout card;
    //To save informations in format of gameInfo.
    private GameInfo gameinfo;
    
    public HolJJackGame() {
        
        initComponents();
        //object initialize
        service=new Service();
        card=(CardLayout) pp.getLayout();
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pp = new javax.swing.JPanel();
        p1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        namev = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        moneyv = new javax.swing.JTextField();
        startGameBtn = new javax.swing.JButton();
        p2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        evenBtn = new javax.swing.JButton();
        quitBtn = new javax.swing.JButton();
        oddBtn = new javax.swing.JButton();
        totalNum = new javax.swing.JLabel();
        winNum = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        moneyLeft = new javax.swing.JLabel();
        p3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        regameBtn = new javax.swing.JButton();
        prizeText = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        winRateText = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pp.setLayout(new java.awt.CardLayout());

        p1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex3/jen1.jpg"))); // NOI18N

        jLabel2.setText("Name:");

        jLabel3.setText("Money:");

        moneyv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moneyvActionPerformed(evt);
            }
        });

        startGameBtn.setText("Play!");
        startGameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startGameBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout p1Layout = new javax.swing.GroupLayout(p1);
        p1.setLayout(p1Layout);
        p1Layout.setHorizontalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(namev, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                            .addComponent(moneyv))
                        .addGap(18, 18, 18)
                        .addComponent(startGameBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        p1Layout.setVerticalGroup(
            p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(p1Layout.createSequentialGroup()
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(namev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(p1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(moneyv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(startGameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE))
                .addContainerGap(203, Short.MAX_VALUE))
        );

        pp.add(p1, "c1");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex3/dsjqucbhtlqbjsnigafsbxfwykchqwszmfa8h3ruhuq9xl4pq2cquuz6bxlgrj53-.jpg"))); // NOI18N

        jLabel5.setText("Total : ");

        jLabel6.setText("Win :");

        evenBtn.setText("even");
        evenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                evenBtnActionPerformed(evt);
            }
        });

        quitBtn.setText("Quit");
        quitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitBtnActionPerformed(evt);
            }
        });

        oddBtn.setText("odd");
        oddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oddBtnActionPerformed(evt);
            }
        });

        jLabel8.setText("Money Left:");

        javax.swing.GroupLayout p2Layout = new javax.swing.GroupLayout(p2);
        p2.setLayout(p2Layout);
        p2Layout.setHorizontalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                .addContainerGap(107, Short.MAX_VALUE)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(p2Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(totalNum, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(winNum))
                        .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p2Layout.createSequentialGroup()
                                .addComponent(oddBtn)
                                .addGap(18, 18, 18)
                                .addComponent(evenBtn)
                                .addGap(18, 18, 18)
                                .addComponent(quitBtn))
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(p2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(moneyLeft)
                        .addGap(197, 197, 197)))
                .addGap(70, 70, 70))
        );
        p2Layout.setVerticalGroup(
            p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(68, 68, 68)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(moneyLeft))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalNum)
                    .addComponent(winNum))
                .addGap(45, 45, 45)
                .addGroup(p2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(evenBtn)
                    .addComponent(quitBtn)
                    .addComponent(oddBtn))
                .addContainerGap(179, Short.MAX_VALUE))
        );

        pp.add(p2, "c2");

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ex3/jen2.jpg"))); // NOI18N

        regameBtn.setLabel("Regame");
        regameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regameBtnActionPerformed(evt);
            }
        });

        jLabel9.setText("Win rate: ");

        javax.swing.GroupLayout p3Layout = new javax.swing.GroupLayout(p3);
        p3.setLayout(p3Layout);
        p3Layout.setHorizontalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(winRateText)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addComponent(prizeText)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(regameBtn)
                        .addGap(23, 23, 23))))
        );
        p3Layout.setVerticalGroup(
            p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 478, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(regameBtn)
                        .addGap(20, 20, 20))
                    .addGroup(p3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(p3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(winRateText))
                        .addGap(5, 5, 5)
                        .addComponent(prizeText)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pp.add(p3, "c3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void moneyvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moneyvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moneyvActionPerformed

    private void startGameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startGameBtnActionPerformed
        // TODO add your handling code here:
        String name=namev.getText();
        //error handle 
        String moneyS=moneyv.getText();
        int money;
        if(moneyS.equals("")){
            JOptionPane.showMessageDialog(this, "Type Money!");
        }else{
            try{
                money=Integer.parseInt(moneyS);
                if(!name.equals("")){
                    namev.requestFocus();
                    
                    //initialize user information
                    service.setInfo(name, money);
                    //initialize card2 window
                    totalNum.setText("0");
                    winNum.setText("0");
                    moneyLeft.setText(String.valueOf(money));
                    card.show(pp, "c2");
                }
                else
                    JOptionPane.showMessageDialog(this, "type name!");
                    
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(this, "Only Integer!");
            }
        }
            
        
    }//GEN-LAST:event_startGameBtnActionPerformed

    private void oddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oddBtnActionPerformed
        // TODO add your handling code here:
        //oddnumber represents 1.
        setGamePlay(1);
            
    }//GEN-LAST:event_oddBtnActionPerformed

    private void evenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_evenBtnActionPerformed
        // TODO add your handling code here:
        //evennumber represents 1.
        setGamePlay(0);
    }//GEN-LAST:event_evenBtnActionPerformed


//method gets executed every time user click odd/even button
    private void setGamePlay(int oddEven){
       
        //if money is enough to play
        if(!service.gamePlay(oddEven)){
           JOptionPane.showMessageDialog(this, "Not Enough Money!");
        }
        else{
        //saves gameinfo from service to gameinfo to display info to window
        //changes information shown on card2 window. 
            gameinfo=service.getGameInfo();
             totalNum.setText(Integer.toString(gameinfo.getTotal()));
             winNum.setText(Integer.toString(gameinfo.getWin()));
             moneyLeft.setText(String.valueOf(gameinfo.getMoney()));
        }
        
        
    }
    private void quitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitBtnActionPerformed
        // TODO add your handling code here:
        
        //If user didn't play minimum rounds of play. 
        if(gameinfo.getCount()>1){
             JOptionPane.showMessageDialog(this, "최소플레이횟수가 "+(gameinfo.getCount()-1)+"회 남았습니다.");
        }
        else{
              
        String winRate=service.winRate();
        String msg=service.prize();
        winRateText.setText(winRate+"%");
        prizeText.setText(msg);
        card.show(pp, "c3");
            
        }
            
      
        
        
    }//GEN-LAST:event_quitBtnActionPerformed

    private void regameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regameBtnActionPerformed
        // TODO add your handling code here:
        service.init(5);
        namev.setText("");
        moneyv.setText("");
        card.show(pp, "c1");
    }//GEN-LAST:event_regameBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HolJJackGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HolJJackGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HolJJackGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HolJJackGame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HolJJackGame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton evenBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel moneyLeft;
    private javax.swing.JTextField moneyv;
    private javax.swing.JTextField namev;
    private javax.swing.JButton oddBtn;
    private javax.swing.JPanel p1;
    private javax.swing.JPanel p2;
    private javax.swing.JPanel p3;
    private javax.swing.JPanel pp;
    private javax.swing.JLabel prizeText;
    private javax.swing.JButton quitBtn;
    private javax.swing.JButton regameBtn;
    private javax.swing.JButton startGameBtn;
    private javax.swing.JLabel totalNum;
    private javax.swing.JLabel winNum;
    private javax.swing.JLabel winRateText;
    // End of variables declaration//GEN-END:variables
}
